jobs:
  include:
  - stage: "Test"
    language: php
    php:
    - 7.2
    addons:
      mariadb: '10.2'
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y nasm
    - mysql -e 'create database IF NOT EXISTS lhr-admin;' -uroot
    - composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest
    - nvm install node
    - npm -v
    - yarn -v
    - yarn install
    install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate -vvv -n
    - yarn run prod
    - php artisan route:cache
    
